#!/bin/bash

USERNAME=rc15129
NAME=$(date +'%Y%m%d%H%M%S')

if [ -e job.sh ]; then
    sed -i '/#PBS -m/d' job.sh
    sed -i '2i\#PBS -m ae' job.sh
    time=$(awk -v result="`grep walltime job.sh`" 'BEGIN {gsub("^.*walltime=","",result); print substr(result,1,8)}')
    ssh $USERNAME@snowy.cs.bris.ac.uk mkdir $NAME
    find . -maxdepth 1 ! -path "./results" ! -path "." | xargs -iz scp -r z $USERNAME@snowy.cs.bris.ac.uk:~/$NAME/ &>/dev/null
    JOB=$(ssh $USERNAME@snowy.cs.bris.ac.uk -t "
    
    #start of snowy script
    scp -r $NAME $USERNAME@bluecrystalp3.bris.ac.uk:~/$NAME &>/dev/null
    rm -rf ~/$NAME/*
    ssh $USERNAME@bluecrystalp3.bris.ac.uk -t '
    
    #start of BC script
    cd $NAME
    qsub job.sh

    ' 2>/dev/null
    " 2>/dev/null
    ) 
    JOB=$(echo $JOB | tr -d '\r')
    echo Submitted $JOB 

    (SLEEPTIME=$(echo $time | sed -E 's/(.*):(.+):(.+)/\1*3600+\2*60+\3/;s/(.+):(.+)/\1*60+\2/' | bc)

    ssh $USERNAME@snowy.cs.bris.ac.uk -t "
    ssh $USERNAME@bluecrystalp3.bris.ac.uk -t \"
    while [ 1 ]
    do
        STATUS=\\\$(grep -A 14 'Subject: PBS JOB $JOB' /var/spool/mail/$USERNAME)
        if [[ \\\$STATUS == *Exit_status* ]]; then
            break
        fi
        sleep $(($SLEEPTIME / 5))
    done
    \"
    
    #cleanup on BC
    cd $NAME
    scp -r $USERNAME@bluecrystalp3.bris.ac.uk:~/$NAME/* . &>/dev/null
    ssh $USERNAME@bluecrystalp3.bris.ac.uk -t 'rm -rf ~/$NAME'
    " &>/dev/null

    #cleanup on Snowy
    mkdir ./results 2>/dev/null
    scp -r $USERNAME@snowy.cs.bris.ac.uk:~/$NAME/ ./results/$JOB/ &>/dev/null
    ssh $USERNAME@snowy.cs.bris.ac.uk -t "rm -rf ~/$NAME" &>/dev/null
    find . -maxdepth 1 ! -path "./results" ! -path "." | xargs -iz rm -rf ./results/$JOB/z

    #notify about results - might not work on OSX / some Linux
    notify-send -u critical "Results recieved for $JOB"
    ) &
else
    echo No job.sh found
fi
